# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\Spoorthy\Desktop\python1\project2.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1074, 673)
        self.lblExam1 = QtWidgets.QLabel(Form)
        self.lblExam1.setGeometry(QtCore.QRect(340, 100, 171, 41))
        self.lblExam1.setStyleSheet("font: 20pt \"MS Shell Dlg 2\";")
        self.lblExam1.setObjectName("lblExam1")
        self.lblExam2 = QtWidgets.QLabel(Form)
        self.lblExam2.setGeometry(QtCore.QRect(340, 170, 131, 41))
        self.lblExam2.setStyleSheet("font: 20pt \"MS Shell Dlg 2\";")
        self.lblExam2.setObjectName("lblExam2")
        self.lblExam3 = QtWidgets.QLabel(Form)
        self.lblExam3.setGeometry(QtCore.QRect(340, 240, 131, 41))
        self.lblExam3.setStyleSheet("font: 20pt \"MS Shell Dlg 2\";")
        self.lblExam3.setObjectName("lblExam3")
        self.txt1 = QtWidgets.QLineEdit(Form)
        self.txt1.setGeometry(QtCore.QRect(520, 100, 201, 41))
        self.txt1.setStyleSheet("font: 20pt \"MS Shell Dlg 2\";")
        self.txt1.setObjectName("txt1")
        self.txt2 = QtWidgets.QLineEdit(Form)
        self.txt2.setGeometry(QtCore.QRect(520, 170, 201, 41))
        self.txt2.setStyleSheet("font: 20pt \"MS Shell Dlg 2\";")
        self.txt2.setObjectName("txt2")
        self.txt3 = QtWidgets.QLineEdit(Form)
        self.txt3.setGeometry(QtCore.QRect(520, 240, 201, 41))
        self.txt3.setStyleSheet("font: 20pt \"MS Shell Dlg 2\";")
        self.txt3.setObjectName("txt3")
        self.btnOutput = QtWidgets.QPushButton(Form)
        self.btnOutput.setGeometry(QtCore.QRect(590, 320, 131, 41))
        self.btnOutput.setStyleSheet("font: 22pt \"MS Shell Dlg 2\";\n"
"font: 18pt \"MS Shell Dlg 2\";")
        self.btnOutput.setObjectName("btnOutput")
        self.lblOutput = QtWidgets.QLabel(Form)
        self.lblOutput.setGeometry(QtCore.QRect(50, 400, 201, 41))
        self.lblOutput.setStyleSheet("font: 14pt \"MS Shell Dlg 2\";")
        self.lblOutput.setObjectName("lblOutput")
        self.lblCoeff = QtWidgets.QLabel(Form)
        self.lblCoeff.setGeometry(QtCore.QRect(50, 450, 181, 41))
        self.lblCoeff.setStyleSheet("font: 14pt \"MS Shell Dlg 2\";")
        self.lblCoeff.setObjectName("lblCoeff")
        self.lblIntercept = QtWidgets.QLabel(Form)
        self.lblIntercept.setGeometry(QtCore.QRect(50, 510, 181, 41))
        self.lblIntercept.setStyleSheet("font: 14pt \"MS Shell Dlg 2\";")
        self.lblIntercept.setObjectName("lblIntercept")
        self.lblFinal = QtWidgets.QLabel(Form)
        self.lblFinal.setGeometry(QtCore.QRect(50, 590, 181, 31))
        self.lblFinal.setStyleSheet("font: 14pt \"MS Shell Dlg 2\";")
        self.lblFinal.setObjectName("lblFinal")
        self.lblHeading = QtWidgets.QLabel(Form)
        self.lblHeading.setGeometry(QtCore.QRect(270, 30, 531, 51))
        self.lblHeading.setStyleSheet("font: 26pt \"MS Shell Dlg 2\";\n"
"color: rgb(85, 0, 127)")
        self.lblHeading.setAlignment(QtCore.Qt.AlignCenter)
        self.lblHeading.setObjectName("lblHeading")
        self.lbl1 = QtWidgets.QLabel(Form)
        self.lbl1.setGeometry(QtCore.QRect(250, 400, 241, 41))
        self.lbl1.setStyleSheet("font: 16pt \"MS Shell Dlg 2\";")
        self.lbl1.setText("")
        self.lbl1.setObjectName("lbl1")
        self.lbl2 = QtWidgets.QLabel(Form)
        self.lbl2.setGeometry(QtCore.QRect(240, 510, 711, 41))
        self.lbl2.setStyleSheet("font: 16pt \"MS Shell Dlg 2\";")
        self.lbl2.setText("")
        self.lbl2.setObjectName("lbl2")
        self.lbl3 = QtWidgets.QLabel(Form)
        self.lbl3.setGeometry(QtCore.QRect(250, 460, 311, 41))
        self.lbl3.setStyleSheet("font: 16pt \"MS Shell Dlg 2\";")
        self.lbl3.setText("")
        self.lbl3.setObjectName("lbl3")
        self.lbl4 = QtWidgets.QLabel(Form)
        self.lbl4.setGeometry(QtCore.QRect(250, 590, 301, 41))
        self.lbl4.setStyleSheet("font: 16pt \"MS Shell Dlg 2\";")
        self.lbl4.setText("")
        self.lbl4.setObjectName("lbl4")
        self.line = QtWidgets.QFrame(Form)
        self.line.setGeometry(QtCore.QRect(20, 380, 1041, 16))
        self.line.setStyleSheet("")
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Project2"))
        self.lblExam1.setText(_translate("Form", "Exam 1"))
        self.lblExam2.setText(_translate("Form", "Exam 2"))
        self.lblExam3.setText(_translate("Form", "Exam 3"))
        self.btnOutput.setText(_translate("Form", "OUTPUT"))
        self.lblOutput.setText(_translate("Form", "Predicted Output :"))
        self.lblCoeff.setText(_translate("Form", "Coefficient :"))
        self.lblIntercept.setText(_translate("Form", "y-Intercept :"))
        self.lblFinal.setText(_translate("Form", "Final Score :"))
        self.lblHeading.setText(_translate("Form", "Multiple Linear Regression"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
